sonar.projectKey=healthcare-platform-management-system-client
sonar.projectName=Healthcare Platform Management System Client
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://127.0.0.1:9000
sonar.login=sqp_9e2861be687388696b6361127c365bc0bc698cb0


