sonar.projectKey=healthcare-platform-management-system-client
sonar.projectName=Healthcare Platform Management System Client
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.host.url=http://127.0.0.1:9000
sonar.login=squ_5479120c6c145e096082a296cc839dd210071ee5
